openapi: 3.0.0
info:
  title: WEEK-10 - API documentaion
  version: 1.0.0
  description: 'Backend API for transferring money' 
servers:
  - url: http://localhost:3000/   
paths:
  /:
    get:
      summary: Get homepage
      responses:
        '200':
          description: Successful response
  /users/register:
    post:
      summary: Register user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: Successful response
  /users/login:
    post:
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful response
  /users/users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful response
  /auth/:
    get:
      summary: Get all transfers
      responses:
        '200':
          description: Successful response
  /auth/transfer:
    post:
      summary: Create transfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                sourceAccount:
                  type: string
                destinationAccount:
                  type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
  /auth/transfer/:
    patch:
      summary: Update transfer
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to be updated
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Successful response
  /transfers/:
    delete:
      summary: Delete transfer
      responses:
        '200':
          description: Successful response
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
